apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-mlflow
spec:
  capacity:
    storage: 5Gi # Adjust this according to your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07ab59687408a6326  # Replace FileSystemId with your EFS File System ID, e.g., fs-07ab59687408a6326
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-mlflow-pvc
  namespace: mlflow
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

