---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ap-efs-mlflow-main-pv
  labels:
    type: ap-efs-mlflow-main-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07ab59687408a6326::fsap-0c9e38253c474887c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ap-efs-mlflow-main-pvc
  namespace: mlflow
spec:
  selector:
    matchLabels:
      type: ap-efs-mlflow-main-pv
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ap-efs-mlflow-main-server
  namespace: mlflow
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/max-scale: '2'
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/min-scale: '0'
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: 1m5s
        autoscaling.knative.dev/target: '15'
        autoscaling.knative.dev/terminationGracePeriodSeconds: '60'
    spec:
      containers:
      - image: public.ecr.aws/y2o2u1i0/mlflow-ecr:latest
        ports:
        - containerPort: 5000
        env:  # Add this section
        - name: MLFLOW_BACKEND_STORE_URI
          value: "file:///main/mlflow/mlruns"
        resources:
          limits:
            cpu: 2
            memory: 5Gi
          requests:
            cpu: 0.1
            memory: 100Mi
        volumeMounts: # <-- Add this section
        - name: efs-mlflow-volume
          mountPath: "/main/mlflow" # Replace this with the path where you want the volume to be mounted inside the container
      volumes: # <-- Add this section
      - name: efs-mlflow-volume
        persistentVolumeClaim:
          claimName: ap-efs-mlflow-main-pvc
      timeoutSeconds: 60
